version: '2'

volumes:
  ctptester_psql:
    external:
      name: ctptester_psql

networks:
  ctptester:
    external:
      name: ctptester

services:
  redis:
    image: redis:5.0-rc
    container_name: ctptester_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      ctptester:
        aliases:
            - redis
  postresql:
    image: postgres:9.5
    container_name: ctptester_psql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ctptester
      POSTGRES_USER: ctptester
      POSTGRES_DB: postgres
    volumes:
      - ctptester_psql:/var/lib/postgresql/data
    restart: always
    networks:
      ctptester:
        aliases:
            - db
  web:
    container_name: web
    image: ctp_testr:latest
    user: root
    ports:
      - 8000:8000
    command: /usr/bin/supervisord -n
  #    restart: always
    volumes:
      - .:/home/project
      - ./.conf/supervisor.d:/etc/supervisor/conf.d:ro
    depends_on:
      - postresql
      - redis
    networks:
      ctptester:
        aliases:
          - web