# Generated by Django 2.0.6 on 2018-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Иван', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='second_name',
            field=models.CharField(default='Иванов', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
