# Generated by Django 2.0.6 on 2018-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180712_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='custompermission',
            options={'ordering': ('content_type__app_label', 'content_type__model', 'codename'), 'verbose_name': 'Разрешение', 'verbose_name_plural': 'Разрешения'},
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='account.CustomPermission', verbose_name='разешения'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
