# Generated by Django 2.0.6 on 2018-07-12 09:54

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180712_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='300x300',
            field=image_cropping.fields.ImageCropField(null=True, upload_to='', verbose_name=models.ImageField(default='avatars/default-user.png', upload_to='avatars/', verbose_name='Аватар')),
        ),
    ]
