# Generated by Django 2.0.6 on 2018-07-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_300x300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='300x300',
        ),
    ]
