# Generated by Django 2.0.6 on 2018-07-12 10:23

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_account_300x300'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='100x100',
            field=image_cropping.fields.ImageCropField(null=True, upload_to='', verbose_name=models.ImageField(default='avatars/default-user.png', upload_to='avatars/', verbose_name='Аватар')),
        ),
    ]
