# Generated by Django 2.0.6 on 2018-07-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_100x100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='100x100',
            new_name='cropping',
        ),
    ]
