# Generated by Django 2.0.6 on 2018-07-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180712_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cropping',
        ),
    ]
