# Generated by Django 2.0.6 on 2018-07-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_account_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ForeignKey(blank=True, default=1, help_text='Группа к которой принадлежит пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
