# Generated by Django 2.0.6 on 2018-07-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('account', '0015_auto_20180712_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, default=1, help_text='Группа к которой принадлежит пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
