# Generated by Django 2.0.6 on 2018-07-13 07:09

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180713_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=image_cropping.fields.ImageCropField(default='avatars/default-user.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
