# Generated by Django 2.0.6 on 2018-07-13 08:23

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180713_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=image_cropping.fields.ImageCropField(default='avatars/default-user.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
