# Generated by Django 2.0.7 on 2018-07-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180713_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ForeignKey(blank=True, default=3, help_text='Группа к которой принадлежит пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Группа'),
        ),
    ]
