# Generated by Django 2.0.7 on 2018-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180718_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группа к которой принадлежит пользователь', related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Группа'),
        ),
    ]
