# Generated by Django 2.0.7 on 2018-07-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180718_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа к которой принадлежит пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
