# Generated by Django 2.0.7 on 2018-07-31 06:43

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20180720_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='custompermission',
            options={'ordering': ('content_type__app_label', 'content_type__model', 'codename'), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissons'},
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=image_cropping.fields.ImageCropField(default='avatars/default-user.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Register date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, help_text='User group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', related_query_name='user', to='account.CustomGroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Set user permissions', related_name='user_set', related_query_name='user', to='account.CustomPermission', verbose_name='User permissions'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='account.CustomPermission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
