# Generated by Django 2.0.6 on 2018-07-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('precondition', models.TextField(blank=True, default='', verbose_name='Предварительные условия')),
                ('excepted_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('status', models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('0', 'Успешно'), ('1', 'Провалено')], default='0', max_length=20, verbose_name='Статус')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.Case', verbose_name='Кейс')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запускал')),
            ],
            options={
                'verbose_name': 'Лог кейса',
                'verbose_name_plural': 'Логи кейсов',
            },
        ),
    ]
