# Generated by Django 2.0.6 on 2018-07-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': '', 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
    ]
