# Generated by Django 2.0.7 on 2018-07-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0002_auto_20180712_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': (('edit_case', 'Может редактировать кейсы'),), 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
    ]
