# Generated by Django 2.0.7 on 2018-07-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0003_auto_20180718_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('1', 'Success'), ('2', 'Failed')], default='0', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='status',
            field=models.CharField(choices=[('0', 'Success'), ('1', 'Failed')], default='0', max_length=20, verbose_name='Статус'),
        ),
    ]
