# Generated by Django 2.0.7 on 2018-08-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0004_auto_20180731_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.Case', verbose_name='Кейс'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='status',
            field=models.CharField(choices=[('0', 'Успешно'), ('1', 'Провалено')], default='0', max_length=20, verbose_name='Статус'),
        ),
    ]
