# Generated by Django 2.0.7 on 2018-08-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0007_auto_20180813_0850'),
        ('test_cases', '0005_auto_20180813_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='plan_run_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_plans.PlanLog', verbose_name='Лог плана'),
            preserve_default=False,
        ),
    ]
