# Generated by Django 2.0.7 on 2018-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0006_caselog_plan_run_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='status',
            field=models.CharField(choices=[('0', 'Провалено'), ('1', 'Успешно')], default='0', max_length=20, verbose_name='Статус'),
        ),
    ]
