# Generated by Django 2.0.6 on 2018-07-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=30)),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
        migrations.CreateModel(
            name='PlanCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=30)),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.Case')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plans.Plan')),
            ],
            options={
                'verbose_name': 'Отношение',
                'verbose_name_plural': 'Отношения',
            },
        ),
        migrations.CreateModel(
            name='PlanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('status', models.CharField(choices=[('0', 'Успешно'), ('1', 'Провалено')], default='0', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plans.Plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Лог плана',
                'verbose_name_plural': 'Логи планов',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='cases',
            field=models.ManyToManyField(through='test_plans.PlanCases', to='test_cases.Case'),
        ),
        migrations.AddField(
            model_name='plan',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан'),
        ),
    ]
