# Generated by Django 2.0.6 on 2018-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancases',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Коментарий'),
        ),
    ]
