# Generated by Django 2.0.7 on 2018-07-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0002_auto_20180717_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planlog',
            old_name='date',
            new_name='last_run',
        ),
    ]
