# Generated by Django 2.0.7 on 2018-07-17 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_plans', '0003_auto_20180717_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancases',
            name='run_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запущен'),
            preserve_default=False,
        ),
    ]
