# Generated by Django 2.0.7 on 2018-07-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0005_auto_20180717_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancases',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('1', 'Success'), ('2', 'Failed')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='plancases',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('1', 'Success'), ('2', 'Failed')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='planlog',
            name='status',
            field=models.CharField(choices=[('0', 'Success'), ('1', 'Failed')], default='0', max_length=30),
        ),
    ]
