# Generated by Django 2.0.7 on 2018-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0006_auto_20180731_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='plancases',
            name='status',
            field=models.CharField(choices=[('0', 'Не выполнялось'), ('1', 'Успешно'), ('2', 'Провалено')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='planlog',
            name='status',
            field=models.CharField(choices=[('0', 'Успешно'), ('1', 'Провалено')], default='0', max_length=30),
        ),
    ]
