# Generated by Django 2.0.7 on 2018-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0007_auto_20180813_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlog',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='planlog',
            name='status',
            field=models.CharField(choices=[('0', 'Провалено'), ('1', 'Успешно')], default='1', max_length=30),
        ),
    ]
