# Generated by Django 2.0.7 on 2018-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plans', '0008_auto_20180814_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск'),
        ),
    ]
